#!/bin/bash

# Wofi Emoji Picker
# Quick emoji selection and copying to clipboard

# Emoji database - commonly used emojis with descriptions
EMOJIS=(
    "😀 grinning face"
    "😂 face with tears of joy"
    "🥰 smiling face with hearts"
    "😊 smiling face with smiling eyes"
    "🤗 hugging face"
    "🤔 thinking face"
    "😉 winking face"
    "😍 smiling face with heart-eyes"
    "🥺 pleading face"
    "😢 crying face"
    "😭 loudly crying face"
    "😤 face with steam from nose"
    "😡 pouting face"
    "🥶 cold face"
    "🥵 hot face"
    "🤯 exploding head"
    "🤐 zipper-mouth face"
    "🤨 face with raised eyebrow"
    "😐 neutral face"
    "😑 expressionless face"
    "😬 grimacing face"
    "🙄 face with rolling eyes"
    "😴 sleeping face"
    "🤤 drooling face"
    "🤗 hugging face"
    "🤭 face with hand over mouth"
    "🤫 shushing face"
    "🤥 lying face"
    "😇 angel"
    "🥸 disguised face"
    "🤓 nerd face"
    "🧐 face with monocle"
    "😎 smiling face with sunglasses"
    "🥸 disguised face"
    "🤡 clown face"
    "👹 ogre"
    "👺 goblin"
    "👻 ghost"
    "💀 skull"
    "👽 alien"
    "🤖 robot"
    "🙈 see-no-evil monkey"
    "🙉 hear-no-evil monkey"
    "🙊 speak-no-evil monkey"
    "💋 kiss mark"
    "💌 love letter"
    "💘 heart with arrow"
    "💝 heart with ribbon"
    "💖 sparkling heart"
    "💗 growing heart"
    "💓 beating heart"
    "💞 revolving hearts"
    "💕 two hearts"
    "💟 heart decoration"
    "❣️ heart exclamation"
    "💔 broken heart"
    "❤️ red heart"
    "🧡 orange heart"
    "💛 yellow heart"
    "💚 green heart"
    "💙 blue heart"
    "💜 purple heart"
    "🤎 brown heart"
    "🖤 black heart"
    "🤍 white heart"
    "💯 hundred points"
    "💢 anger symbol"
    "💥 collision"
    "💫 dizzy"
    "💦 sweat droplets"
    "💨 dashing away"
    "🕳️ hole"
    "💣 bomb"
    "💬 speech balloon"
    "👁️‍🗨️ eye in speech bubble"
    "🗨️ left speech bubble"
    "🗯️ right anger bubble"
    "💭 thought balloon"
    "💤 zzz"
    "👋 waving hand"
    "🤚 raised back of hand"
    "🖐️ hand with fingers splayed"
    "✋ raised hand"
    "🖖 vulcan salute"
    "👌 ok hand"
    "🤌 pinched fingers"
    "🤏 pinching hand"
    "✌️ victory hand"
    "🤞 crossed fingers"
    "🤟 love-you gesture"
    "🤘 sign of the horns"
    "🤙 call me hand"
    "👈 backhand index pointing left"
    "👉 backhand index pointing right"
    "👆 backhand index pointing up"
    "🖕 middle finger"
    "👇 backhand index pointing down"
    "☝️ index pointing up"
    "👍 thumbs up"
    "👎 thumbs down"
    "👊 oncoming fist"
    "✊ raised fist"
    "🤛 left-facing fist"
    "🤜 right-facing fist"
    "👏 clapping hands"
    "🙌 raising hands"
    "👐 open hands"
    "🤲 palms up together"
    "🤝 handshake"
    "🙏 folded hands"
    "✍️ writing hand"
    "💅 nail polish"
    "🤳 selfie"
    "💪 flexed biceps"
    "🦾 mechanical arm"
    "🦿 mechanical leg"
    "🦵 leg"
    "🦶 foot"
    "👂 ear"
    "🦻 ear with hearing aid"
    "👃 nose"
    "🧠 brain"
    "🫀 anatomical heart"
    "🫁 lungs"
    "🦷 tooth"
    "🦴 bone"
    "👀 eyes"
    "👁️ eye"
    "👅 tongue"
    "👄 mouth"
    "🖼️ framed picture"
    "🎨 artist palette"
    "🧵 thread"
    "🧶 yarn"
    "👓 glasses"
    "🕶️ sunglasses"
    "🥽 goggles"
    "🥼 lab coat"
    "🦺 safety vest"
    "👔 necktie"
    "👕 t-shirt"
    "👖 jeans"
    "🧣 scarf"
    "🧤 gloves"
    "🧥 coat"
    "🧦 socks"
    "👗 dress"
    "👘 kimono"
    "🥻 sari"
    "🩱 one-piece swimsuit"
    "🩲 briefs"
    "🩳 shorts"
    "👙 bikini"
    "👚 woman's clothes"
    "👛 purse"
    "👜 handbag"
    "👝 clutch bag"
    "🛍️ shopping bags"
    "🎒 backpack"
    "🩴 thong sandal"
    "👞 man's shoe"
    "👟 running shoe"
    "🥾 hiking boot"
    "🥿 flat shoe"
    "👠 high-heeled shoe"
    "👡 woman's sandal"
    "🩰 ballet shoes"
    "👢 woman's boot"
    "👑 crown"
    "👒 woman's hat"
    "🎩 top hat"
    "🎓 graduation cap"
    "🧢 billed cap"
    "⛑️ rescue worker's helmet"
    "📿 prayer beads"
    "💄 lipstick"
    "🪮 hair pick"
    "💍 ring"
    "💎 gem stone"
)

# Function to copy to clipboard
copy_to_clipboard() {
    local emoji="$1"
    echo -n "$emoji" | wl-copy
    echo "$emoji wurde in die Zwischenablage kopiert!"
}

# Show emoji menu with wofi
SELECTED=$(printf '%s\n' "${EMOJIS[@]}" | wofi --dmenu --prompt "Emoji suchen:" --width 600 --height 400 --location center --gtk-dark)

# Extract emoji from selection
if [ -n "$SELECTED" ]; then
    EMOJI=$(echo "$SELECTED" | cut -d' ' -f1)
    copy_to_clipboard "$EMOJI"
fi
